name: basearch
description: Flutter Sample Architecture Project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.2
  localization: ^2.1.0
  flutter_svg: ^1.0.3
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  dio: ^4.0.6
  confetti: ^0.6.0
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.0-nullsafety
  encrypted_shared_preferences: ^3.0.0
  validators: ^3.0.0
  json_annotation: ^4.4.0
  flutter_smart_dialog: ^3.4.2+2
  charts_flutter: ^0.12.0
  geolocator: ^8.2.1
  google_maps_flutter: ^2.1.5
  dotenv: ^4.0.1
  dash_chat_2: ^0.0.6
  uuid: ^3.0.6
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.5
  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.8
  flutter_config: ^2.0.0

flutter:

  assets:
    - lib/assets/
    - lib/assets/i18n/
    - lib/assets/images/
    - lib/assets/styles/

  fonts:
     - family: Poppins
       fonts:
         - asset: lib/assets/fonts/Poppins-Regular.ttf
         - asset: lib/assets/fonts/Poppins-SemiBold.ttf
         - asset: lib/assets/fonts/Poppins-Bold.ttf

  uses-material-design: true
  
  


