INSERT INTO TYPE_SESSION (ID, TYPE) VALUES ('1','LOGIN') ON CONFLICT DO NOTHING;
INSERT INTO TYPE_SESSION (ID, TYPE) VALUES ('2','RESET_PASSWORD') ON CONFLICT DO NOTHING;
INSERT INTO TYPE_SESSION (ID, TYPE) VALUES ('3','REFRESH_TOKEN') ON CONFLICT DO NOTHING;

INSERT INTO TYPE_MEASURE (ID, TYPE) VALUES ('1','TEMPERATURE') ON CONFLICT DO NOTHING;
